config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  root "welcome#index"

  resources :coins
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
# frozen_string_literal: true

# Coin model
class Coin < ApplicationRecord
  belongs_to :mining_type

  validates :description, presence: true, length: {
    minimum: 3,
    maximum: 200,
    too_short: 'description is too short',
    too_long: 'description is too long'
  }
  validates :url_image, presence: true, http_url: { message: 'invalid URL' }
  validates :acronym, presence: true, format: { with: /[A-Z0-9]/, message: 'invalid acronym format' }
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application controller
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    cookies[:lang] = params[:lang] || cookies[:lang] || I18n.default_locale

    locale = cookies[:lang]

    return I18n.with_locale(I18n.default_locale, &action) unless I18n.available_locales.include?(locale.to_sym)

    I18n.with_locale(locale, &action)
  end
end

app/controllers/coins_controller.rb
# frozen_string_literal: true

# Coins Controller
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[show edit update destroy]
  before_action :set_mining_type_options, only: %i[create new edit update]
  add_flash_types :error

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
    return unless @coin.nil?

    respond_to do |format|
      format.html { redirect_to coins_url, error: 'This coin was not found' }
    end
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit; end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_mining_type_options
    @mining_type_options = MiningType.all.pluck(:description, :id)
  end

  def set_coin
    @coin = Coin.find_by_id(params[:id])
  end

  def coin_params
    params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
  end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Welcome Controller
class WelcomeController < ApplicationController
  include WelcomeHelper

  def index
    return unless params.key? :name

    @name = format_name params[:name]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application helper
module ApplicationHelper
  def application_name
    'Crypto Wallet'
  end

  def show_flash(message, type)
    return if message.nil?

    content_tag(:p, message, class: "flash #{type}")
  end

  def development_banner
    return unless Rails.env.development?

    content_tag(:p, 'development', class: 'dev_banner')
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def format_name(name = '')
    name.strip.camelize
  end
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <p>
    <strong>Description:</strong>
    <%= coin.description %>
  </p>

  <p>
    <strong>Acronym:</strong>
    <%= coin.acronym %>
  </p>

  <p>
    <strong>Url image:</strong>
    <%= coin.url_image %>
  </p>

</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.label :url_image, style: "display: block" %>
    <%= form.text_field :url_image %>
  </div>

  <div>
    <%= form.label :mining_type, style: "display: block" %>
    <%= form.select("mining_type_id", @mining_type_options, { include_blank: false }) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Show this coin", @coin %> |
  <%= link_to "Back to coins", coins_path %>
</div>

app/views/coins/index.html.erb
<main class="wrapper">
  <%= show_flash error, :error %>
  <%= show_flash notice, :success %>

  <h1 class="title"><%= application_name %></h1>

  <ul class="coins">
    <% @coins.each do |coin| %>
      <li class="coin">
        <div class="coin_head">
          <% unless coin.url_image.empty?  %>
            <%= image_tag coin.url_image, class: "coin_image" %>
          <% end %>

          <p><%= coin.acronym %> - <%= coin.description %></p>
        </div>

        <div class="links">
          <%= link_to t('links.show'), coin_path(coin), class: "link"  %>
          <%= link_to t('links.edit'), edit_coin_path(coin), class: "link" %>
        </div>
      </li>
    <% end %>
  </ul>

  <%= link_to t('links.new'), new_coin_path, class: "new" %>
</main>

app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Back to coins", coins_path %>
</div>

app/views/coins/show.html.erb
<main class="wrapper">
  <%= show_flash error, :error %>
  <%= show_flash notice, :success %>

  <div class="coin">
    <div class="coin_head">
      <% unless @coin.url_image.empty?  %>
        <%= image_tag @coin.url_image, class: "coin_image" %>
      <% end %>

      <p><%= @coin.acronym %> - <%= @coin.description %></p>
    </div>

    <div class="links">
      <%= link_to t('links.edit'), edit_coin_path(@coin), class: "link" %>
      <%= button_to t('links.delete'), @coin, method: :delete, class: "link" %>
    </div>
  </div>

  <div class="actions">
    <%= link_to "Back to coins", coins_path, class: "link" %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= development_banner %>

    <%= yield %>

    <footer>
      <label for="select-language"><%= t 'select_language' %></label>
      <select id="select-language" placeholder="<%= t 'select_language' %>">
        <option value='pt-BR' <%= 'selected' if cookies[:lang] == 'pt-BR' %>>Português - Brasil</option>
        <option value='en' <%= 'selected' if cookies[:lang] == 'en' %>>English - US</option>
      </select>
    </footer>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <p>
    <strong><%= MiningType.human_attribute_name(:description) %></strong>
    <%= mining_type.description %>
  </p>

  <p>
    <strong><%= MiningType.human_attribute_name(:acronym) %></strong>
    <%= mining_type.acronym %>
  </p>

</div>

app/views/mining_types/edit.html.erb
<h1>Editing mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to t('links.edit'), @mining_type %> |
  <%= link_to "Back to mining types", mining_types_path %>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mining types</h1>

<div id="mining_types">
  <% @mining_types.each do |mining_type| %>
    <%= render mining_type %>
    <p>
      <%= link_to t('links.show'), mining_type %>
    </p>
  <% end %>
</div>

<%= link_to t('links.new'), new_mining_type_path %>

app/views/mining_types/new.html.erb
<h1>New mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Back to mining types", mining_types_path %>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mining_type %>

<div>
  <%= link_to t('links.edit'), edit_mining_type_path(@mining_type) %> |
  <%= link_to "Back to mining types", mining_types_path %>

  <%= button_to t('links.delete'), @mining_type, method: :delete %>
</div>

app/views/welcome/_menu.html.erb
<ul style="margin-top: 2rem;">
  <li>
    <%= link_to "Minhas moedas", coins_path %>
    <%= link_to "Tipos de mineração", mining_types_path %>
  </li>
</ul>

app/views/welcome/index.html.erb
<%= render "menu" %>